### ISSUE TITLE
i got 2 external errors

### ISSUE THREAD

**Issue by suciuale** [wiotq/Externalit#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "unsigned int sdk::offys::m_bDormant" (?m_bDormant@offys@sdk@@3IA)	csgo_external	D:\csgo_external\csgo_external\entity.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "unsigned int sdk::offys::m_zoomLevel" (?m_zoomLevel@offys@sdk@@3IA)	csgo_external	D:\csgo_external\csgo_external\weapon.obj	1

**Comment by wiotq** [comment]
I fucked up with updating sdk.cpp, just pushed update.
https://github.com/wiotq/Externalit/blob/master/csgo_external/csgo_external/sdk/sdk.cpp
